spring.application.name=bai5_qlsp
spring.datasource.url=jdbc:mysql://localhost:3306/bai5_qlsp?useSSL=false&serverTimezone=UTC&characterEncoding=UTF-8
spring.datasource.username=root
# Thay đổi 123456 thành mật khẩu MySQL trên máy của bạn
spring.datasource.password=

# Cấu hình Hibernate tự động cập nhật cấu trúc bảng
spring.jpa.hibernate.ddl-auto=update